### ISSUE TITLE
Rm codemetar from Suggests?

### ISSUE THREAD

**Issue by maelle** [mikemahoney218/proceduralnames#1]
This is a suggestion. :-) You'd need to fix the GitHub Actions workflow that uses codemetar.

I'm asking because I'm preparing a release of codemetar, and this package isn't really a reverse dependency of codemetar. :-)

**Comment by mikemahoney218** [comment]
Yup, can do. I'm assuming this needs to get to CRAN to be useful for you?

I can also survey my other CRAN packages and fix there.

**Comment by maelle** [comment]
no, no hurry at all, it won't prevent codemetar to reach CRAN! It'll just be easier for next time I look at the rev deps. :-) Only this package and another one not by you had the dependency.

**Comment by maelle** [comment]
(and thank you!)

**Comment by mikemahoney218** [comment]
Sent a version 0.1.2 removing codemetar to CRAN, hopefully it'll be updated within a few days :smile: Feel free to let me know if we ever run into any other similar situations!

**Comment by maelle** [comment]
Thank you!
